### ISSUE TITLE
Perwell Quest - acq15002.bcs

### ISSUE THREAD

**Issue by RoxanneSHS** [whiteagnus/AC_QUEST#3]
In EET
Perwell did not follow me out of the Cloakwood to FAA when I freed him and triggered the respective dialogue.
I added this to acq150002.bcs to solve the issue

IF
    Global("ACQ15","GLOBAL",4)
    Global("Make","Locals",0)
THEN
    RESPONSE #100
        SetGlobal("Make","Locals",1)
        MakeGlobal()
        ChangeEnemyAlly(Myself,GOODBUTBLUE)
        MoveGlobalObject("acq15002",Player1)
END

**Comment by Gitjas** [comment]
This is included in v2.01

**Comment by RoxanneSHS** [comment]
Included in mod
